services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: psy_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - REDIS_ADDR=redis:6379
    volumes:
      - .:/app
    command: go run main.go

volumes:
  postgres_data:
  redis_data: